import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es">
        <body style={{ fontFamily:'system-ui, sans-serif', maxWidth:720, margin:'0 auto', padding:16 }}>
        <nav style={{ display:'flex', gap:12, marginBottom:16 }}>
            <a href="/">Inicio</a>
            <a href="/login">Login</a>
            <a href="/tasks">Tareas</a>
        </nav>
        {children}
        </body>
        </html>
    );
}

