import type { Metadata } from "next";
import "./globals.css";
import QuickBar from "./components/QuickBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false
  }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es">
        <body style={{ fontFamily:'system-ui, sans-serif', maxWidth:720, margin:'0 auto', padding:16 }}>
        <QuickBar/>
        {children}
        </body>
        </html>
    );
}

